name: CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Install package
      run: cd cicd && npm install
    - name: Testing
      run: cd cicd && npm run test
  deploy_cloudrun:
    needs: test
    name: Trigger Google Cloud Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.RUN_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Start Google Cloud Build trigger'
      run: |
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        gcloud beta builds triggers run ${{ secrets.RUN_CB_TRIGGER }} --branch master
